spring:
  datasource:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/mydb
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
     hibernate:
        ddl-auto: none
     show-sql: true
     database-platform: org.hibernate.dialect.MySQL5Dialect
     properties:
       hibernate:
         enable_lazy_load_no_trans: true
  thymeleaf:
     mode: LEGACYHTML5
     cache: false
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE

  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 100
        max-wait: 100
server:
  port: 8088
